-- 1. Create the table safely with constraints (Copilot Suggestion #1)
create table if not exists public.mottos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  language text not null,
  content text not null,
  author text not null,

  -- Constraints to ensure data quality
  constraint mottos_unique_language_content unique (language, content), -- Prevents duplicate quotes in the same language
  constraint content_not_empty check (length(trim(content)) > 0),       -- Prevents empty quotes
  constraint author_not_empty check (length(trim(author)) > 0),         -- Prevents empty authors
  constraint valid_language check (length(trim(language)) > 0)          -- Prevents empty language codes
);

-- 2. Enable RLS
alter table public.mottos enable row level security;

-- 3. Create Policy efficiently (Copilot Suggestion #4)
-- PostgreSQL supports 'IF NOT EXISTS' for policies, which is cleaner than the DO block
create policy if not exists "Enable read access for all users"
on public.mottos for select
using (true);

-- 4. Add Performance Index (Copilot Suggestion #3)
-- Speeds up filtering by language, which will be a common operation
create index if not exists idx_mottos_language on public.mottos(language);

-- 5. Insert Seed Data with Conflict Handling (Copilot Suggestion #2)
-- Using 'ON CONFLICT DO NOTHING' is safer than checking if table is empty.
-- It ensures missing quotes are added without creating duplicates if some already exist.
insert into public.mottos (language, content, author)
values
  ('en', 'The only way to do great work is to love what you do.', 'Steve Jobs'),
  ('en', 'The expert in anything was once a beginner.', 'Helen Hayes'),
  ('en', 'Believe you can and you''re halfway there.', 'Theodore Roosevelt'),
  ('en', 'Learning is a treasure that will follow its owner everywhere.', 'Chinese Proverb'),
  ('en', 'The beautiful thing about learning is that no one can take it away from you.', 'B.B. King'),
  ('pl', 'Jedynym sposobem na wielką pracę jest kochanie tego, co robisz.', 'Steve Jobs'),
  ('pl', 'Ekspert w każdej dziedzinie był kiedyś początkującym.', 'Helen Hayes'),
  ('pl', 'Uwierz, że potrafisz, a będziesz w połowie drogi.', 'Theodore Roosevelt'),
  ('pl', 'Nauka to skarb, który podąża za właścicielem wszędzie.', 'Przysłowie chińskie'),
  ('pl', 'Piękno nauki polega na tym, że nikt nie może ci jej odebrać.', 'B.B. King'),
  ('uk', 'Єдиний спосіб робити велику роботу - це любити те, що ти робиш.', 'Стів Джобс'),
  ('uk', 'Експерт у будь-якій справі колись був новачком.', 'Хелен Хейз'),
  ('uk', 'Повір, що ти можеш, і ти вже на півдорозі до мети.', 'Теодор Рузвельт'),
  ('uk', 'Навчання - це скарб, який буде слідувати за своїм власником всюди.', 'Китайське прислів''я'),
  ('uk', 'Прекрасне в навчанні те, що ніхто не може його у вас відібрати.', 'Б.Б. Кінг')
on conflict (language, content) do nothing;